version: '3.9'

services:
  kong-migrations:
    image: kong:3.6
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST: ${KONG_PG_HOST}
      KONG_PG_USER: ${KONG_PG_USER}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
      KONG_PG_DATABASE: ${KONG_PG_DATABASE}
    command: kong migrations bootstrap
    restart: on-failure
    networks:
      - bdbazar-net
  kong:
    image: kong:3.6
    container_name: kong
    depends_on:
      - kong-migrations
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST: ${KONG_PG_HOST}
      KONG_PG_USER: ${KONG_PG_USER}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
      KONG_PG_DATABASE: ${KONG_PG_DATABASE}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    ports:
      - "8060:8000"   # Proxy port
      - "8443:8443"   # Proxy SSL port
      - "8002:8001"   # Admin API
      - "8444:8444"   # Admin API SSL
    restart: unless-stopped
    networks:
      - bdbazar-net

networks:
  bdbazar-net:
    external: true
