version: '3.9'

services:
  admin-service:
    image: bdbazar/admin-service:latest
    container_name: bdbazar-admin-service
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${ADMIN_SERVICE_PORT:-8090}:8090"
    environment:
      - PORT=${ADMIN_SERVICE_PORT}
      - DB_SOURCE=host=${DB_HOST} user=${DB_USER} password=${DB_PASS} dbname=${ADMIN_DB_NAME} port=${DB_PORT} sslmode=${DB_SSLMODE}
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_SERVICE_URL=http://auth-service:${AUTH_SERVICE_PORT}
      - ENVIRONMENT=${ENV}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - bdbazar-net

networks:
  bdbazar-net:
    external: true
